// Generated by deploy.sh — do not edit manually.
window._deployLive = {
  dashboard:  { frontend: true,  backend: true  },
  nextjs:     { frontend: true,  backend: true  },
  fargate:    { frontend: false,  backend: false  },
  serverless: { frontend: false,  backend: false  },
};
