#!/usr/bin/env bash
set -e
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
CREDS="$REPO_DIR/.emailjs"

_encode() { python3 -c "import urllib.parse,sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$1"; }

_seed_url() {
  source "$CREDS"
  echo "http://localhost:9090?s=$(_encode "$EJS_S")&t=$(_encode "$EJS_T")&k=$(_encode "$EJS_K")&e=$(_encode "$EJS_E")"
}

case "${1:-}" in
  dev)
    if [[ ! -f "$CREDS" ]]; then
      printf '\nNo .emailjs creds found — starting one-time setup to configure the contact form.\n'
      exec "$0" setup
    fi
    open "$(_seed_url)" &
    echo "Serving at http://localhost:9090"
    python3 -m http.server 9090 --directory "$REPO_DIR"
    ;;
  setup)
    printf '\n╔══════════════════════════════════════════════╗\n'
    printf '║           EmailJS One-Time Setup             ║\n'
    printf '╚══════════════════════════════════════════════╝\n'
    printf '\nThe contact form sends email via EmailJS.\n'
    printf 'Log in or create a free account at: https://www.emailjs.com\n'
    printf '\n── Where to find each value ──────────────────────────────────\n'
    printf '  Service ID   Left nav → Email Services → your service row\n'
    printf '  Template ID  Left nav → Email Templates → your template row\n'
    printf '  Public Key   Top-right avatar → Account → API Keys\n'
    printf '\n── Template variables (paste these into your EmailJS template body) ─\n'
    printf '  {{from_email}}  the email address the visitor types in the form\n'
    printf '  {{project}}     auto-filled: which project was clicked\n'
    printf '  {{requested}}   auto-filled: which artifact was requested\n'
    printf '\n── Contact email ─────────────────────────────────────────────\n'
    printf '  The address EmailJS will deliver to (your inbox).\n'
    printf '─────────────────────────────────────────────────────────────\n\n'
    read -rp 'Service ID    : ' EJS_S
    read -rp 'Template ID   : ' EJS_T
    read -rp 'Public Key    : ' EJS_K
    read -rp 'Contact email : ' EJS_E
    printf 'EJS_S=%s\nEJS_T=%s\nEJS_K=%s\nEJS_E=%s\n' "$EJS_S" "$EJS_T" "$EJS_K" "$EJS_E" > "$CREDS"
    echo "Saved to .emailjs"
    python3 -m http.server 9090 --directory "$REPO_DIR" &>/dev/null &
    SERVER_PID=$!
    sleep 0.4
    open "$(_seed_url)"
    printf '\nBrowser localStorage seeded. Press Enter to stop the server...'
    read -r
    kill "$SERVER_PID" 2>/dev/null || true
    ;;
  ""|deploy)
    cd "$REPO_DIR"

    _yn() {
      local prompt="$1" default="${2:-y}" ans
      read -rp "  $prompt (y/n) [$default]: " ans
      ans="${ans:-$default}"
      [[ "$ans" =~ ^[Yy] ]] && echo "true" || echo "false"
    }

    printf '\n━━━ Live endpoint selection ━━━\n\n'
    printf 'GCP Orders Dashboard\n'
    DASH_FE=$(_yn "frontend live?" y)
    DASH_BE=$(_yn "backend API Explorer live?" y)
    printf '\nNext.js Dashboard (AWS)\n'
    NEXT_FE=$(_yn "frontend live?" y)
    NEXT_BE=$(_yn "backend API Explorer live?" y)
    printf '\n'

    FARG_FE=false; FARG_BE=false
    SRVL_FE=false; SRVL_BE=false

    cat > "$REPO_DIR/deploy-live.js" <<EOF
// Generated by deploy.sh — do not edit manually.
window._deployLive = {
  dashboard:  { frontend: $DASH_FE,  backend: $DASH_BE  },
  nextjs:     { frontend: $NEXT_FE,  backend: $NEXT_BE  },
  fargate:    { frontend: $FARG_FE,  backend: $FARG_BE  },
  serverless: { frontend: $SRVL_FE,  backend: $SRVL_BE  },
};
EOF

    git add index.html deploy-live.js
    if ! git diff --cached --quiet; then
      git commit -m "deploy: update live endpoint selection"
    fi
    git push origin main
    gh workflow run "Deploy Pages" --repo bganguly/bganguly.github.io --ref main
    echo "Triggered. Check: gh run list --repo bganguly/bganguly.github.io"
    ;;
  *)
    echo "Usage: $0 [dev|setup|deploy]"
    exit 1
    ;;
esac
