// Generated by deploy.sh — do not edit manually (except phiBackendUrl: set once after first cloud deploy).
window._deployLive = {
  showLlmSection: true,
  dashboard:  { frontend: true,  backend: true  },
  nextjs:     { frontend: true,  backend: true  },
  fargate:    { frontend: false,  backend: false  },
  serverless: { frontend: true,  backend: true  },
  phiBackendUrl: '', // set to Cloud Run URL after first deploy; access controlled by token, not this URL
};
