// Generated by set-live-url.sh — do not edit manually.
window._liveUrls = {
  dashboardLiteFe: 'https://dash-lite-frontend-77y7e2wykq-uc.a.run.app',
  nextjsLiteBe: 'https://d30vaq6r4kp2fu.cloudfront.net/api-explorer',
  nextjsLiteFe: 'https://d30vaq6r4kp2fu.cloudfront.net',
};
