// Generated by set-live-url.sh — do not edit manually.
window._liveUrls = {
  dashboardLiteFe: 'https://dash-lite-frontend-77y7e2wykq-uc.a.run.app',
  nextjsLiteBe: 'https://df9jh7fbcc9nk.cloudfront.net/api-explorer',
  nextjsLiteFe: 'https://df9jh7fbcc9nk.cloudfront.net',
  nlsqlLiteFe: 'https://natural-language-to-llm-query-comparison.vercel.app/nl-to-sql/',
  ragLiteBe: 'https://rjzv5wg32ibpqyz7nd665n3gei0ntgfo.lambda-url.us-east-1.on.aws/',
  ragLiteFe: 'https://frontend-jxqw5zefi-gangulybikramjit-4435s-projects.vercel.app',
  serverlessBe: 'https://d281doisqbuiu2.cloudfront.net/api-explorer.html',
  serverlessFe: 'https://d281doisqbuiu2.cloudfront.net',
};
