// Generated by set-live-url.sh — do not edit manually.
window._liveUrls = {
  clickhouseBe: 'https://d1n8zhx1j8oymk.cloudfront.net/api-explorer',
  clickhouseFe: 'https://d1n8zhx1j8oymk.cloudfront.net',
  dashboardLiteFe: 'https://dash-lite-frontend-77y7e2wykq-uc.a.run.app',
  edgarAgentBe: 'https://edgar-backend-77y7e2wykq-uc.a.run.app',
  edgarAgentFe: 'https://edgar-frontend-77y7e2wykq-uc.a.run.app',
  edgarAgentLiteBe: 'https://edgar-backend-77y7e2wykq-uc.a.run.app',
  edgarAgentLiteFe: 'https://edgar-frontend-77y7e2wykq-uc.a.run.app',
  nextjsLiteBe: 'https://df9jh7fbcc9nk.cloudfront.net/api-explorer',
  nextjsLiteFe: 'https://df9jh7fbcc9nk.cloudfront.net',
  nlsqlLiteFe: 'https://natural-language-to-llm-query-comparison.vercel.app/nl-to-sql/',
  ragLiteBe: 'https://frontend-sigma-ten-30.vercel.app/api-explorer.html',
  ragLiteFe: 'https://frontend-sigma-ten-30.vercel.app',
  serverlessBe: 'https://d3nbn0s3ea4m39.cloudfront.net/api-explorer.html',
  serverlessFe: 'https://d3nbn0s3ea4m39.cloudfront.net',
};
