#!/usr/bin/env bash
set -euo pipefail
# Usage: set-live-url.sh [--tier <lite|full>] <project_key> <fe_url> [<be_url>]
# Called by each app's deploy.sh after a successful cloud deploy.
# Updates portfolio/live-urls.js, commits, and pushes bganguly.github.io.

PORTFOLIO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LIVE_URLS_FILE="$PORTFOLIO_DIR/live-urls.js"

TIER=""
while [[ "${1:-}" == --* ]]; do
  case "$1" in
    --tier) TIER="$2"; shift 2 ;;
    *) shift ;;
  esac
done

PROJECT="${1:?Usage: set-live-url.sh [--tier lite|full] <project_key> <fe_url> [be_url]}"
FE_URL="${2:?fe_url is required}"
BE_URL="${3:-}"

python3 - <<PYEOF
import re, os

live_urls_file = "$LIVE_URLS_FILE"
project   = "$PROJECT"
tier      = "$TIER"
fe_url    = "$FE_URL"
be_url    = "$BE_URL"

tier_cap  = tier.capitalize() if tier else ''
key_fe    = project + tier_cap + 'Fe'
key_be    = project + tier_cap + 'Be'

urls = {}
if os.path.exists(live_urls_file):
    for m in re.finditer(r"(\w+):\s*'([^']*)'", open(live_urls_file).read()):
        urls[m.group(1)] = m.group(2)

urls[key_fe] = fe_url
if be_url:
    urls[key_be] = be_url

lines = ["// Generated by set-live-url.sh — do not edit manually.", "window._liveUrls = {"]
for k in sorted(urls):
    lines.append(f"  {k}: '{urls[k]}',")
lines.append("};")
open(live_urls_file, 'w').write('\n'.join(lines) + '\n')
label = f"{project}/{tier}" if tier else project
print(f"live-urls.js updated ({label}).")
PYEOF

cd "$PORTFOLIO_DIR"
git add live-urls.js
if ! git diff --cached --quiet; then
  git commit -m "deploy: update ${PROJECT}${TIER:+/${TIER}} live URL"
  git push origin HEAD:main
  echo "Portfolio pushed — Pages rebuilds in ~30s."
else
  echo "No change to live-urls.js."
fi
