#!/usr/bin/env bash
set -euo pipefail
# Usage: set-live-url.sh <project_key> <fe_url> [<be_url>]
# Called by each app's deploy.sh after a successful cloud deploy.
# Updates portfolio/live-urls.js, commits, and pushes bganguly.github.io.

PORTFOLIO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LIVE_URLS_FILE="$PORTFOLIO_DIR/live-urls.js"

PROJECT="${1:?Usage: set-live-url.sh <project_key> <fe_url> [be_url]}"
FE_URL="${2:?fe_url is required}"
BE_URL="${3:-}"

python3 - <<PYEOF
import re, os, sys

live_urls_file = "$LIVE_URLS_FILE"
project   = "$PROJECT"
fe_url    = "$FE_URL"
be_url    = "$BE_URL"

urls = {}
if os.path.exists(live_urls_file):
    for m in re.finditer(r"(\w+):\s*'([^']*)'", open(live_urls_file).read()):
        urls[m.group(1)] = m.group(2)

urls[project + 'Fe'] = fe_url
if be_url:
    urls[project + 'Be'] = be_url

lines = ["// Generated by set-live-url.sh — do not edit manually.", "window._liveUrls = {"]
for k in sorted(urls):
    lines.append(f"  {k}: '{urls[k]}',")
lines.append("};")
open(live_urls_file, 'w').write('\n'.join(lines) + '\n')
print("live-urls.js updated.")
PYEOF

cd "$PORTFOLIO_DIR"
git add live-urls.js
if ! git diff --cached --quiet; then
  git commit -m "deploy: update ${PROJECT} live URL"
  git push origin HEAD:main
  echo "Portfolio pushed — Pages rebuilds in ~30s."
else
  echo "No change to live-urls.js."
fi
